import { useEffect } from 'react';

const COPY: Record<string, { title: string; body: string }> = {
  privacy: {
    title: 'Privacy Policy',
    body: 'Last updated: October 2026. FreeLMS ("we") is a free learning platform. This policy explains what we collect and why. It is a plain-language summary, not legal advice.\n\n1. ACCOUNT DATA WE STORE\nWhen you sign in (Google or email), we store your name, email address and profile photo in our database to run your account. If you use email sign-in, login credentials are handled by our authentication provider; we never see your password.\n\n2. LEARNING DATA WE STORE\nTo make the platform work, we save your course enrollments, completed lessons, quiz attempts and scores, notes, bookmarks, learning paths progress, daily activity (for streaks) and badges. This data syncs across your devices and is visible only to you and our administrators.\n\n3. WHAT WE DO NOT COLLECT\nNo advertising profiles, no cross-site tracking, no sale of personal data. We run no ads and use no third-party analytics that follows you around the web.\n\n4. YOUTUBE EMBEDS\nLessons play videos through YouTube\'s official embedded player, streamed from YouTube. When you watch, Google\'s privacy policy and YouTube\'s terms apply to that playback (as on youtube.com), including cookies Google may set. We do not control Google\'s data practices.\n\n5. ON-DEVICE STORAGE\nWe use your browser\'s local storage for preferences (theme, dismissed announcements) and short-lived caches (course lists). Clearing site data signs you out of nothing but resets these preferences.\n\n6. DATA SHARING\nWe share nothing with advertisers or data brokers. Data is processed by our infrastructure providers (authentication, database) solely to operate the service, and may be disclosed if required by law.\n\n7. CHILDREN\nFreeLMS is a general learning platform not directed at children under 13. If you believe a child provided us data, contact us and we will delete it.\n\n8. YOUR RIGHTS & DELETION\nYou can edit your name and photo on the Profile page. To erase everything — profile, enrollments, notes, attempts, bookmarks — use Profile → Delete account (permanently removes your data and login). For any privacy request, email us at the address below and we respond within 30 days.\n\n9. CHANGES\nIf this policy changes materially, we will post the new version here with a new date. Continued use after changes means you accept them.'
  },
  terms: {
    title: 'Terms of Use',
    body: 'Last updated: October 2026. By using FreeLMS you agree to these terms. Plain-language summary, not legal advice.\n\n1. FREE PERSONAL LEARNING\nFreeLMS is free for personal, non-commercial learning. No fees, no ads, no premium tiers. We may add, change or discontinue features at any time.\n\n2. ACCOUNTS\nYou are responsible for activity under your account. Provide accurate details, keep your login safe, and tell us about unauthorized use. We may suspend accounts that abuse the service, post harmful content or interfere with other learners.\n\n3. VIDEOS BELONG TO THEIR CREATORS\nAll videos are embedded from YouTube and remain the property of their creators — see our Content Disclaimer. You may watch and learn, but you may not download, re-upload, scrape or commercially exploit course content or other users\' contributions. Creator takedown requests are honored within 48 hours.\n\n4. YOUR CONTRIBUTIONS\nNotes are private to you. Discussion posts, reports and feedback you submit must be lawful, respectful and yours to share. You grant us a license to display your public contributions (e.g. discussion posts) for operating the platform. We may hide or remove content that violates these terms.\n\n5. ACCEPTABLE USE\nNo spam, harassment, hate speech, malware, attempts to breach security or rate limits, or any use that harms learners, creators or the service.\n\n6. NO WARRANTIES\nThe service and all content are provided "as is" without warranties of any kind. Learning outcomes depend on your effort; we do not guarantee results, accuracy of third-party videos, or uninterrupted availability.\n\n7. LIABILITY\nTo the maximum extent permitted by law, FreeLMS is not liable for indirect, incidental or consequential damages arising from your use of the service.\n\n8. CHANGES & CONTACT\nWe may update these terms; material changes will be posted here with a new date. Questions: contact us at the email below.'
  },
  about: {
    title: 'About FreeLMS — Free Online Courses Platform',
    body: 'FreeLMS is a free online courses platform for everyone. We curate the best free video training from independent creators — web development, freelancing, AI and digital skills — and turn scattered playlists into structured courses: enroll in seconds, follow a syllabus and timetable, track lesson-by-lesson progress, test yourself with quizzes, keep timestamped notes, join the discussion and earn your skills.\n\nHOW IT WORKS\nPick a free course and enroll in one click. Your progress, quiz attempts, notes, bookmarks and streaks save to your account automatically and follow you across devices. Everything is free, with no ads and no fees — learn anything, at your pace.\n\nHOW WE USE VIDEOS (THE SHORT VERSION)\nWe do not download, copy, re-upload, edit or claim anyone\'s videos. Every lesson plays the original video through YouTube\'s official embedded player, streamed from YouTube itself — so every watch counts as a view for the creator, exactly as on YouTube. Each lesson links the creator\'s channel and the original video, sending students to subscribe and explore more.\n\nGOOD FOR BOTH SIDES\nStudents get a focused learning platform instead of an entertainment feed: syllabus, quizzes, notes, timetables and certificates of progress. Creators get views, watch time, subscribers and full credit — a curated showcase in front of motivated learners. Read the full Content Disclaimer for details.\n\nFOR CREATORS\nWe feature creators to celebrate and amplify their work. Want a video featured, credited differently, or removed for any reason? Email us or use the "Report or takedown request" link on any course or video — we act within 48 hours, no questions asked.'
  },
  disclaimer: {
    title: 'Content Disclaimer — How FreeLMS Uses YouTube Videos',
    body: 'HOW WE SHOW VIDEOS\nWe do not download, copy, re-upload, edit or claim anyone\'s videos. Every lesson plays the original video through YouTube\'s official embedded player, streamed directly from YouTube\'s servers. What you watch here is the creator\'s own upload, on the creator\'s own channel.\n\nWHY THIS HELPS CREATORS (NOT HURTS THEM)\n• Every view counts: watching a lesson here registers as a view on the original YouTube video, exactly as if you watched it on YouTube.\n• Watch time and engagement flow to the creator\'s channel, supporting their growth and revenue.\n• Discovery: each lesson links the creator\'s channel and the original video, sending students to subscribe and explore more of their work.\n• Showcase, not theft: we act as a curated shelf that puts quality creators in front of motivated learners who would never have found them otherwise.\n\nWHAT STUDENTS GET\nYouTube is built for entertainment; FreeLMS is built for learning. The same free videos, reorganized into structured courses with a syllabus, progress tracking, quizzes, timestamped notes, timetables and discussion — so a scattered playlist becomes a complete course.\n\nWHAT WE NEVER DO\n• Never re-upload or mirror videos on our servers or any other platform.\n• Never strip, hide or replace creator credits, watermarks or branding.\n• Never charge for access to someone else\'s content and never place our own ads over it.\n• Never claim ownership of any video, thumbnail, title or description.\n\nFOR CREATORS: PERMISSION & TAKEDOWN\nWe feature creators to celebrate and amplify their work, and we always link back. If you are a creator and you want your video featured, credited differently, or removed — for any reason, no questions asked — email us from the address below and we will act within 48 hours. Use the "Report or takedown request" link on any course or video for the fastest response.\n\nIN SHORT\nStudents get a focused, free learning platform. Creators get views, subscribers and full credit. Good for both — that is the entire idea behind FreeLMS.\n\nThis page explains our approach in plain language and is not legal advice.'
  }
};

export function StaticPage({ kind }: { kind: 'privacy' | 'terms' | 'about' | 'disclaimer' }) {
  const c = COPY[kind];
  useEffect(() => { document.title = `${c.title} | FreeLMS`; }, [kind, c.title]);
  if (!c) return null;
  return (
    <div className="mx-auto max-w-2xl px-3 py-6">
      <div className="card p-6"><h1 className="font-bold">{c.title}</h1><p className="mt-2 text-sm whitespace-pre-wrap">{c.body}</p>
      <p className="mt-2 text-sm">Contact: {import.meta.env.VITE_CONTACT_EMAIL}</p></div>
    </div>
  );
}
